packages:
  - 'packages/*'
  - 'crates/*'
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: false
blockExoticSubdeps: false
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@mizdra/*'
  - vite-plus
  - vite
  - vitest
  - '@voidzero-dev/*'
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
overrides:
  vite: '$vite'
  vitest: '$vitest'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
